project:
  type: website
  output-dir: docs
  resources: 
    - "*.mp4"

website:
  title: "**CSCI1012**"
  # back-to-top-navigation: true
  page-footer: "The course material is sourced from **Prof. Simha's** webpage: <https://www2.seas.gwu.edu/~simhaweb/onlinecs1012/> <br>This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>."
  search: true
  sidebar:
    style: floating
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: schedule.qmd
        text: Schedule
      - href: course-policies.qmd
        text: Course Policies
      - href: instructors.qmd
        text: Instruction Team

      - ./submit-remember.qmd
      - ./units/useful.qmd
      - section: "Getting Started"
        contents: 
        - ./units/unit0/editor.qmd
      - section: "Units"
        contents: 
          - section: "**Unit 0:** Getting Started With Programming"
            contents:
              - ./units/unit0/modules/module0.0.qmd
              - ./units/unit0/modules/module0.1.qmd
              - ./units/unit0/modules/module0.2.qmd
              - ./units/unit0/modules/module0.3.qmd
              - ./units/unit0/modules/module0.4.qmd
              - ./units/unit0/modules/module0.5.qmd
              - ./units/unit0/modules/module0.6.qmd
          - section: "**Unit 1:** Key Building Blocks in Programming"
            contents: 
              - ./units/unit1/modules/module1.0.qmd
              - ./units/unit1/modules/module1.1.qmd
              - ./units/unit1/modules/module1.2.qmd
              - ./units/unit1/modules/module1.3.qmd
              - ./units/unit1/modules/module1.4.qmd
              - ./units/unit1/modules/module1.5.qmd
          - section: "**Unit 2:** Advanced Topics and Applications"
            contents: 
              - ./units/unit2/modules/module2.0.qmd
              - ./units/unit2/modules/module2.1.qmd
              - ./units/unit2/modules/module2.2.qmd
      - href: faq.qmd
        text: FAQ
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem


