project:
  type: website
  output-dir: docs

website:
  title: "**CSCI1012**"
  back-to-top-navigation: true
  page-footer: "This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>."
  search: true
  sidebar:
    contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: coursework.qmd
        text: Coursework
      - href: faq.qmd
        text: FAQ
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem


