project:
  type: website
  output-dir: docs
  resources: 
    - "*.mp4"
    - "*.mov"

website:
  title: "**CSCI1012**"
  # back-to-top-navigation: true
  page-footer: "The course material is sourced from **Prof. Simha's** webpage: <https://www2.seas.gwu.edu/~simhaweb/onlinecs1012/> <br>This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>."
  search: true
  page-navigation: true
  bread-crumbs: true
  sidebar:
    style: floating
    # collapse-level: 2
    contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: schedule.qmd
        text: Schedule
      - href: course-policies.qmd
        text: Course Policies
      - href: ./units/unit2/modules/advising.qmd
        text: CS Minor advising
      - href: instructors.qmd
        text: Instruction Team
      - ./submit-remember.qmd
      - ./units/useful.qmd
      - section: "Getting Started"
        contents: 
          - ./units/unit0/editor.qmd
          - ./units/unit0/guides/hello.qmd
          - ./units/unit0/guides/writing-your-first-program.qmd
      - section: "Units"
        contents: 
          - section: "**Unit 0:** Getting Started With Programming"
            contents:
              - ./units/unit0/modules/module0.qmd
              - ./units/unit0/modules/module1.qmd
              - ./units/unit0/modules/module2.qmd
              - ./units/unit0/modules/module3.qmd
              - ./units/unit0/modules/module4.qmd
              - ./units/unit0/modules/module5.qmd
              - ./units/unit0/modules/module6.qmd
          - section: "**Unit 1:** Key Building Blocks in Programming"
            contents: 
              - ./units/unit1/modules/module0.qmd
              - ./units/unit1/modules/module1.qmd
              - ./units/unit1/modules/module2.qmd
              - ./units/unit1/modules/module3.qmd
              - ./units/unit1/modules/module4.qmd
              - ./units/unit1/modules/module5.qmd
          - section: "**Unit 2:** Advanced Topics and Applications"
            contents: 
              - ./units/unit2/modules/module0.qmd
              - ./units/unit2/modules/module1.qmd
              - ./units/unit2/modules/module2.qmd
          - section: "Additional Resources"
            contents: 
              - section: "Instructor Notes"
                contents:   
                  - href: units/additional-resources/insructor-notes/week-1.qmd
                    text: "Week-1"
                  - href: units/additional-resources/insructor-notes/week-2.qmd
                    text: "Week-2"
                  - href: units/additional-resources/insructor-notes/week-3.qmd
                    text: "Week-3"
                  - href: units/additional-resources/insructor-notes/week-4.qmd
                    text: "Week-4"
                  - href: units/additional-resources/insructor-notes/week-5.qmd
                    text: "Week-5"
                  - href: units/additional-resources/insructor-notes/week-6.qmd
                    text: "Week-6"
                  - href: units/additional-resources/insructor-notes/week-7.qmd
                    text: "Week-7"
                  - href: units/additional-resources/insructor-notes/week-9.qmd
                    text: "Week-9"
                  - href: units/additional-resources/insructor-notes/week-10.qmd
                    text: "Week-10"
                  - href: units/additional-resources/insructor-notes/week-11.qmd
                    text: "Week-11"
                  - href: units/additional-resources/insructor-notes/week-12.qmd
                    text: "Week-12"
                  - href: units/additional-resources/insructor-notes/week-14.qmd
                    text: "Week-14"
              - section: "Lab Notes"
                contents: 
                  - section: "Amal AlQahtani"
                    contents: 
                      - href: ./units/additional-resources/lab-notes/amal/week-1.qmd
                        text: "Week-1"
              - href: units/additional-resources/minor-advising.qmd
                text: "Computer Science Minor Advising"
      # - section: "Assignments"
      #   contents:
      #     - ./units/unit0/assignments/assignment0.qmd
      #     - ./units/unit0/assignments/assignment1.qmd
      #     - ./units/unit1/assignments/assignment2.qmd
      #     - ./units/unit1/assignments/assignment3.qmd
      #     - ./units/unit2/assignments/assignment4.qmd
      - href: faq.qmd
        text: FAQ
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem


