---
title: "About"
---

<!-- <div class="breadcrumbs">
  <a href="./index.qmd">Home</a> &raquo;
  <span class="current-page">About</span>
</div> -->

## Instructor
### **Dr. Kartik Bulusu**

**Email:** <a href="mailto:bulusu@gwu.edu">Dr. Kartik Bulusu</a><br>

## Course Learning Outcomes
- Demonstrate familiarity with key concepts in a procedural programming language such as: variables, control structures, functions, input and output.
- Demonstrate the ability to use programming to solve problems appropriate to a beginning class in programming.
- Acquire familiarity with how programming can be applied to solve problems.


## Time & Location of the course
- **Monday Lecture**
    - Room [**1957 E Room 213**](https://it.gwu.edu/classroom-search/1957-e-street-213)

:::{.callout-note}
Lecture times are from **3:45 PM – 5:00 PM**
:::

- **Wednesday Lab**
    - Section 30: *Moved to* Room [**MONROE HALL 352**](https://it.gwu.edu/classroom-search/monroe-hall-352), will no longer meet at [**1957 E Room 310**](https://it.gwu.edu/classroom-search/1957-e-street-310)
    - Section 31: Room [**SEH 4040**](https://it.gwu.edu/classroom-search/science-and-engineering-hall-4040)
    - Section 34: Room [**TOMP 310**](https://it.gwu.edu/classroom-search/tompkins-hall-310)
    - Section 35: Room [**TOMP 204**](https://it.gwu.edu/classroom-search/tompkins-hall-204)

- **Friday Lab**
    - Section 32: Room [**SEH 4040**](https://it.gwu.edu/classroom-search/science-and-engineering-hall-4040)
    - Section 33: *Moved to* Room [**TOMP 309**](https://it.gwu.edu/classroom-search/tompkins-hall-309)
    - Section 36: *Moved to* Room [**TOMP 306**](https://it.gwu.edu/classroom-search/tompkins-hall-306)
    - Section 37: Room [**TOMP 107**](https://it.gwu.edu/classroom-search/tompkins-hall-107)

:::{.callout-note}
All laboratory sections will meet from **3:45 PM – 5:00 PM**
:::

## Office Hours
_Current Office Hour Schedule is listed below:_
```{=html}
<table style="width:100%">
    <thead>
        <tr class="table-info">
            <th>Day(s)</th>
            <th>Time</th>
            <th>Location</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Tuesdays</td>
            <td>4:00 PM to 5:00 PM</td>
            <td>SEH 4th Floor</td>
        </tr>
        <tr class="table-active">
            <td>Wednesdays</td>
            <td>10:00 AM to 1:00 PM</td>
            <td>SEH 4th Floor</td>
        </tr>
        <tr>
            <td>Wednesdays</td>
            <td>5:00 PM to 6:15 PM</td>
            <td>SEH 4th Floor</td>
        </tr>
        <tr class="table-active">
            <td>Thursdays</td>
            <td>3:30 PM to 5:00 PM</td>
            <td>SEH 4th Floor</td>
        </tr>
        <tr>
            <td>Fridays</td>
            <td>10:00 AM to 1:00 PM</td>
            <td><a href="https://it.gwu.edu/classroom-search/science-and-engineering-hall-b1280"><b>SEH B1280</b></a></td>
        </tr>
        <tr class="table-active">
            <td>Fridays</td>
            <td>1:45 PM to 2:45 PM</td>
            <td><a href="https://it.gwu.edu/classroom-search/science-and-engineering-hall-b1280"><b>SEH B1280</b></a></td>
        </tr>
        <tr>
            <td>Fridays</td>
            <td>5:15 PM to 6:15 PM</td>
            <td>SEH 4th Floor</td>
        </tr>
    </tbody>
</table>
```

:::{.callout-note}
Please be advised that the office hour schedule will be updated as the semester progresses.
:::

## Why are there no recorded video lectures?
Learning to program by watching some talk about it is less effective than learning by "doing programming". Thus, most of your learning will consist of reading a concept, seeing an example, and immediately following that with a programming exercise that really gets into the details. At the same time, we know it's useful to have hints and explanations to help you in your exercises, when you are particularly stuck. Accordingly, although most of the material is written, and includes elaborate instructions, there is recorded media that you can optionally view/listen if you need it. These are recorded from a student point of view (but carefully vetted by us), as you'll see.

## Teaching Assistants (TAs)
For information about TAs, their office hours and how to reach out to them, please refer the [Instruction Team](instructors.qmd) page.

## Prerequisites
None

## Official catalog description
Introduction to programming a computer using the Python language; variables, types, assignment, conditionals, loops, lists, and program units. _(Fall, spring, and summer, Every Year)._

## Informal description
This course is all about getting started with programming in the language called Python.

## Textbook
All of the material is online (and free)

## Other requirements
- You will be expected to have and use your Blackboard account. If you have trouble logging in, you will need to resolve this by the first meeting.

## Staying on top of the course
- Visit the course website (this one) and the Blackboard part of this course several times each week.
- Be responsive to email sent to you.

## Course load
This is not a light course. The course has three units, each of which has a number of modules. Based on students who've taken the course previously, we've identified the approximate number of hours needed for each module. 

:::{.callout-warning}
The hours needed vary by module, so please plan accordingly. The first unit starts off gently, after which the pace increases. **Unit-1** is the hardest.
:::

## Late work policy
Late work is not accepted, with the following exceptions:

1. Every student may turn in as many as four deliverables (modules or assignments) up to 48 hours after the deadline with no penalty. Requesting an extension is not necessary in these cases.
2. Extensions will be granted should there arise circumstances beyond your control that impede your ability to complete coursework and turn in a deliverable on time. Notify your professor as soon as feasible in these cases. Examples of such circumstances include (but are not limited to) illness, death in the family, and loss of housing. To ensure fairness toward all students, I will request documentation of such circumstances.

## Accommodations
We are committed to accommodating student needs in whatever ways are possible and fair. This includes, but is certainly not limited to, [Disability Support Services](https://www2.seas.gwu.edu/~cs4all/1012/syllabus.html#disability-support-services-dss) (DSS). Let your professor know of circumstances that may impact your academic commitments if and when such circumstances arise, or before the semester begins, as is appropriate. To ensure fairness toward all students, we will request documentation of such circumstances, either directly or via DSS.

## Minimum course load
In a 15-week semester, including exam week, students are expected to spend a minimum of 100 minutes of out-of-class work for every 50 minutes of direct instruction, for a minimum total of 2.5 hours a week. A 3-credit course includes 2.5 hours of direct instruction and a minimum of 5 hours of independent learning, or a minimum of 7.5 hours per week. More information about GW’s credit hour policy can be found at: provost.gwu.edu/policies-forms

## Statement on inclusive teaching
It is my intent that students from all backgrounds and perspectives be well-served by this course, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit. Your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

:::{.callout-note}
That course policies may be adjusted or modified during the course of the semester.
:::