---
title: "CS 1012: Introduction to Programming with Python"
---

### Welcome to CSCI 1012 - Spring 2024:

:::{.callout-caution title="Cource Content" collapse="false"}
The course material is sourced from **Prof. Simha's** webpage: <https://www2.seas.gwu.edu/~simhaweb/onlinecs1012/>
:::

:::{.callout-important title="Make-up Quiz (03/04/2024)" icon="false"}
**Make-up Quiz for all students on Monday, 03/04/2024**

- A make up quiz will be given to all students during the lecture on **Monday, 03/04/2024**
- The quiz will be for the **duration of 15 mins**.
- The quiz will start at the beginning of the lecture time and end in **15 mins**.
    - You should not have any mobile devices (_laptops, cell phones, iPads, other smart devices etc_) in your possession during your quiz.
    - You will not be using any IDE or accessing internet during the quiz.
- You should return the quiz to the proctors or the professor and cannot hold on to it once done.

**Format of the make-up quiz**

- The Quiz will be in same format as the quizzes offered during labs
    - The students will get to answer _4 questions_.
    - Each question will carry _2.5 points_.

**The make up quiz is being given under the following conditions**

- The quiz score can count toward one missed quiz until **03/08/2024** <u>OR</u> the lowest score on a quiz until **03/08/2024**, if you get a better score.
- The make-up is only valid until **03/08/2024**; it will not count toward any quiz from thereon until the end of the course.

**The four lowest quizzes will still be dropped before the final grade.**

**The regular lab quiz on Wednesday and Friday this week will still be given out.**
:::

- **General information**: The course we will meet during lecture and laboratory times each week.
    - Most of our communication to you will be by Blackboard messaging and announcements.
    - Start by reading the [**About**](about.qmd) section. 
    - Review the [**Course policies**](course-policies.qmd) and get familiar with the [**Instruction Team**](instructors.qmd).
    - These are the current [**office hours**](about.qmd#office-hours) being made available. 
    - They will be update as the semester progresses.

- **Student's main method of communication during the semester**: Our main method of communication is Ed, an online discussion board for questions and answers related to the course, whether technical or logistical in nature.
    - [**Join Ed here**](https://edstem.org/us/join/aNhz9P)
    - Do not post your source code to Ed. 
    - Think through your questions. Post a general concept of the programming concept. 
    - Your questions on Ed will be addressed within 24 hours.

- **Course schedule**: The [**Schedule**](schedule.qmd) page outlines the weekly-schedule and what your deliverables are. It is YOUR job to keep to the schedule and submit work accordingly.
    - The first meeting of the course will be during the labs on **Wednesday** _(01/17/2024)_ and **Friday** _(01/19/2024)_ [See [**Schedule**](schedule.qmd)]
    
:::{.callout-warning}
There is a deliverable due on **January  22, 2024** by **11:59 PM**.
:::

- **Getting Started**: You will need to install a Python IDE (Integrated Development Environment).
    - Follow the instructions on [**Installing an Editor**](units/unit0/editor.qmd).
    - Choose **Thonny** (for [_Mac_](units/unit0/guides/thonny-mac.qmd) or [_Windows_](units/unit0/guides/thonny-windows.qmd)) as your primary choice of IDE for its simplicity, especially if you are new to coding. However, you can choose, **Spyder** (for [_Mac_](units/unit0/guides/anaconda-mac.qmd) or [_Windows_](units/unit0/guides/anaconda-windows.qmd)) which is a more versatile alternative. 
    - The course is organized into Units and each Unit (0, 1 and 2) has modules in them. 

- **Submitting your work**: When you submit work, please follow the specific instructions outlined on [**how to submit your work**](submit-remember.qmd).

- **Communication during extenuating circumstances**: When you need to communicate with us directly regarding extenuating circumstances, please use Blackboard or follow the specific instructions outlined in [**Blackboard**](https://blackboard.gwu.edu).
    - The instructor will check emails on Mondays and may respond at their earliest convenience. 
    - Any direct email communication with annyone from the instruction team may not result in a response.

:::{.callout-important}
<!-- - Our staff is limiting the use of Linux OS-based laptops and cannot support them this semester.  -->
- We prefer that your computer has a standard US keyboard layout i.e, a QWERTY keyboard. 
    - The QWERTY (pronounced KWEHR-tee) keyboard is the standard typewriter and computer keyboard in countries that use a Latin-based alphabet.
:::

