---
title: "What to remember about submitting work"
---

## Most important

- The submission requirements are <em>stringent</em>. You MUST name folders and files exactly as described.
- In particular: be careful to avoid spaces where they shouldn't be spaces, and to use <em>lowercase</em> when asked. For example:
    - `module0.pdf` (correct)
    - `Module0.pdf` (wrong: starts with uppercase)
    - `module 0.pdf` (wrong: space before 0)
    - `module0.docx` (wrong: not a pdf).
- Your programs must do what's asked, no less no more. If you print more than what's required the <em>autograder</em> will not grade your program.

If you've forgotten how to make folders, zip files etc, now may be a good time to [review your computerese skills]()

### Another important thing to remember
You will be submitting your PDF files TWICE, once inside the zip file and once separately in Blackboard.

## Correct folder structure on your laptop
For the overall class you should have a folder named `cs1012` on your computer:

- You can create one such folder on your Desktop, but you could also place this inside some other folder.

:::{.callout-warning}
It's all lowercase, with no spaces.
:::

In the cs1012 folder, create a folder for each unit. Eventually, you will create a folder for each unit and each module in a given unit.  

You must name your folders with the following rules:

- There will be 3 units, so you will ultimately have folders called `unit0, unit1` and `unit2` inside your cs1012 folder.
- Name the unit folders carefully:
    - For your Unit 0 work, name that unit's folder `unit0`.
    - For your Unit 1 work, name that unit's folder `unit1`.
    - For your Unit 2 work, name that unit's folder `unit2`.
- Each unit has several modules. For each module folder inside the each unit folder, you must name the module folder according to these rules: Each unit has several modules. For each module folder inside the each unit folder, you must name the module folder according to these rules: 
    - For your Module 0 work, name that module's folder `module0`.
    - For your Module 1 work, name that module's folder `module1`.
    - And so on.
- Each unit has will also have assignments. For each assignment inside each unit, make a folder. You must name the assignment folders according to these rules: 
    - For your Assignment 1 work, name that folder `assignment1`.
    - For your Assignment 2 work, name that folder `assignment2`.
    - And so on if there are more assignments.
- Thus, one looks inside your 1012 folder, we'd expect to see three sub-folders called `unit0, unit1,` and `unit2`. 
- And, if one further looks inside the `unit0` folder, we'd expect to see 9 sub-folders:
    - 7 of these will be called `module0, module1, module2, module3, module4, module5` and `module6`
    - 2 of these will be called `assignment1` and `assignment2`.

## Correct location and naming of files within folders
Every module and every assignment will feature multiple files:

- Most files will be Python programs. The names of these will end in `.py`.
- For example: `myname.py`.
- Another example from Module 0  in Unit 0: In Exercise 0.4, you are instructed to create the files `error1.py` and `error2.py`. These need to be saved in your `module0` folder when using your code editor (Thonny or Spyder).
- Every module will also have a single PDF file with the same first-part named as the module name. For example: you will make a file called `module0.pdf` in your `module0` folder.
- When is the PDF file to be used? The single PDF (one per module) is used when you are to write responses outside of Python code. For example:
    - In Module 0, you are asked to submit a picture and write (in English) something about yourself. You can write in Word, and save to a PDF file called `module0.pdf` in your `module0` folder.
    - In Exercise 1.11 of Module 1, you are asked to describe
    an error. You will describe (in plain English) by writing in `module1.pdf`. Similarly, Exercise 1.8 asks you to describe the output of a program. Copy-paste the output from Thonny/Spyder into  `module1.pdf`. Make sure `module1.pdf` is saved to in your `module1`folder.

## Making a zip to submit
When you zip your files when preparing to submit them, you must zip only the files for the current module and you must name the zip file for the corresponding folder.  

- The easy way to do this is to zip the folder containing the files.  
- For example, for **Unit 0 : Module 1**, you must zip the `module1` folder that is inside the `unit0` folder. Since this folder will contain the `module1.pdf` file, it will get included in the zip file.
- When it's time to submit, you will upload this zip file (example: `module1.zip`) into the _appropriate place in Blackboard_.
